// skin.js — generated by SLOT FORGE（PixiJS 版表現層參數）
// 這份檔案只影響「畫面」，不影響機率：sprite 幀數/時長、中獎特效、噴錢數量、彩帶顏色都在這裡。
// 來源：美術動畫編輯器的設定；想微調也可以直接改這支檔案，重整頁面就生效。
const Skin = {
  "renderer": "pixi",
  "pixiVersion": "8.20.1",
  "sourceGame": "Cascading_PayAnywhere_6x5",
  "motionBlur": true,
  "winFx": {
    "scale": 1.15,
    "brightness": 1.3,
    "glow": "rgb(0, 110, 255)"
  },
  "popFx": {
    "scale": 1.15,
    "brightness": 1.5
  },
  "timing": {
    "reelDelay": 300,
    "spin": 2000,
    "spinTurbo": 1000,
    "fillers": 18,
    "stopPause": 100,
    "landBounce": 300,
    "refill": 400,
    "explode": 400,
    "pulse": 1,
    "pop": 0.8
  },
  "symbols": {
    "1": {
      "win": "pulse",
      "sprite": {
        "src": "s1_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 150
    },
    "2": {
      "win": "pulse",
      "sprite": {
        "src": "s2_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 150
    },
    "3": {
      "win": "pulse",
      "sprite": {
        "src": "s3_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 150
    },
    "4": {
      "win": "pulse",
      "sprite": {
        "src": "s4_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 150
    },
    "5": {
      "win": "pulse",
      "sprite": {
        "src": "s5_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 150
    },
    "6": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "7": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "8": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "9": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "10": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "11": {
      "win": "pop",
      "sprite": {
        "src": "SCATTER_sprite.png",
        "frames": 28,
        "dur": 1.5,
        "loop": true
      },
      "widthScale": 1.15,
      "glow": {
        "color": "rgba(255, 215, 0, 0.8)",
        "blur": 10
      },
      "z": 200,
      "zActive": 800
    },
    "20": {
      "win": "pop",
      "sprite": {
        "src": "eye_sprite.png",
        "frames": 28,
        "dur": 1.5,
        "loop": true
      },
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999
    },
    "21": {
      "win": "pop",
      "sprite": {
        "src": "eye_sprite.png",
        "frames": 28,
        "dur": 1.5,
        "loop": true
      },
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999
    },
    "22": {
      "win": "pop",
      "sprite": {
        "src": "eye_sprite.png",
        "frames": 28,
        "dur": 1.5,
        "loop": true
      },
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999
    },
    "23": {
      "win": "pop",
      "sprite": {
        "src": "eye_sprite.png",
        "frames": 28,
        "dur": 1.5,
        "loop": true
      },
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999
    },
    "24": {
      "win": "pulse",
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 900
    }
  },
  "explosion": {
    "src": "explosion_sprite.png",
    "frames": 15,
    "dur": 0.5,
    "loop": false,
    "size": 2.22,
    "offsetX": -0.08
  },
  "effects": {
    "coinImg": "coin.png",
    "confettiColors": [
      "#ffd700",
      "#ff4500",
      "#00e5ff",
      "#7c4dff",
      "#27e07e"
    ],
    "confettiDurMin": 1.5,
    "confettiDurMax": 3.5,
    "tiers": {
      "big": {
        "coins": 40,
        "confetti": 50
      },
      "mid": {
        "coins": 100
      },
      "small": {
        "coins": 30
      }
    }
  }
};

export default Skin;